<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SubscriptionPlan;

class SubscriptionPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name'              => 'Starter',
                'slug'              => 'starter',
                'monthly_price'     => 29,
                'yearly_price'      => 288, // €24/mo
                'reservation_limit' => 200,
                'max_staff'         => 3,
                'ai_credits_limit'  => 100,
                'sms_credits_limit' => 20,
                'is_popular'        => false,
                'features'          => [
                    // Sectros Standard Entitlement Keys
                    'booking.core'         => true,
                    'booking.public_page'  => true,
                    'booking.floor_plan'   => true,
                    'booking.deposits'     => false,
                    'staff.management'     => false,
                    'staff.time_tracking'  => false,
                    'staff.payroll'        => false,
                    'inbox.unified'        => false,
                    'inbox.whatsapp'       => false,
                    'inbox.facebook'       => false,
                    'inbox.instagram'      => false,
                    'inbox.ai_reply'       => false,
                    'finance.cash_register'=> false,
                    'finance.receipt_scanner' => false,
                    'finance.dashboard'    => false,
                    'finance.exports'      => false,
                    'kiosk.mode'           => false,
                    'kiosk.takeout_orders' => false,
                    'kiosk.menu_manager'   => false,
                    'ai.assistant'         => false,
                    'ai.voice_agent'       => false,
                    'branding.white_label' => false,
                    'api.access'           => false,
                    'locations.max'        => 1,
                    // Legacy & UI Compatibility Aliases
                    'insights'             => true,
                    'reservations'         => true,
                    'configuration'        => true,
                    'provisioning'         => true,
                    'billing_plan'         => true,
                    'menu_builder'         => true,
                    'floor_plan'           => true,
                    'social_integration'   => false,
                    'pos_terminal'         => false,
                    'staff_management'     => false,
                    'financial_reports'    => false,
                    'ai_automation'        => false,
                    'online_ordering'      => false,
                    'inventory_tracking'   => false,
                ],
                'is_active' => true,
            ],
            [
                'name'              => 'Professional',
                'slug'              => 'pro',
                'monthly_price'     => 69,
                'yearly_price'      => 708, // €59/mo
                'reservation_limit' => 1500,
                'max_staff'         => 15,
                'ai_credits_limit'  => 1000,
                'sms_credits_limit' => 200,
                'is_popular'        => true,
                'features'          => [
                    // Sectros Standard Entitlement Keys
                    'booking.core'         => true,
                    'booking.public_page'  => true,
                    'booking.floor_plan'   => true,
                    'booking.deposits'     => true,
                    'staff.management'     => true,
                    'staff.time_tracking'  => true,
                    'staff.payroll'        => true,
                    'inbox.unified'        => true,
                    'inbox.whatsapp'       => true,
                    'inbox.facebook'       => true,
                    'inbox.instagram'      => true,
                    'inbox.ai_reply'       => true,
                    'finance.cash_register'=> true,
                    'finance.receipt_scanner' => true,
                    'finance.dashboard'    => true,
                    'finance.exports'      => true,
                    'kiosk.mode'           => false,
                    'kiosk.takeout_orders' => true,
                    'kiosk.menu_manager'   => true,
                    'ai.assistant'         => true,
                    'ai.voice_agent'       => true,
                    'branding.white_label' => false,
                    'api.access'           => false,
                    'locations.max'        => 1,
                    // Legacy & UI Compatibility Aliases
                    'insights'             => true,
                    'reservations'         => true,
                    'configuration'        => true,
                    'provisioning'         => true,
                    'billing_plan'         => true,
                    'menu_builder'         => true,
                    'floor_plan'           => true,
                    'social_integration'   => true,
                    'pos_terminal'         => true,
                    'staff_management'     => true,
                    'financial_reports'    => true,
                    'ai_automation'        => true,
                    'online_ordering'      => true,
                    'inventory_tracking'   => true,
                    'ai_voice_agent'       => true,
                    'waitlist_automation'  => true,
                ],
                'is_active' => true,
            ],
            [
                'name'              => 'Enterprise',
                'slug'              => 'enterprise',
                'monthly_price'     => 149,
                'yearly_price'      => 1548, // €129/mo
                'reservation_limit' => null,
                'max_staff'         => null,
                'ai_credits_limit'  => 5000,
                'sms_credits_limit' => 1000,
                'is_popular'        => false,
                'features'          => [
                    // Sectros Standard Entitlement Keys
                    'booking.core'         => true,
                    'booking.public_page'  => true,
                    'booking.floor_plan'   => true,
                    'booking.deposits'     => true,
                    'staff.management'     => true,
                    'staff.time_tracking'  => true,
                    'staff.payroll'        => true,
                    'inbox.unified'        => true,
                    'inbox.whatsapp'       => true,
                    'inbox.facebook'       => true,
                    'inbox.instagram'      => true,
                    'inbox.ai_reply'       => true,
                    'finance.cash_register'=> true,
                    'finance.receipt_scanner' => true,
                    'finance.dashboard'    => true,
                    'finance.exports'      => true,
                    'kiosk.mode'           => true,
                    'kiosk.takeout_orders' => true,
                    'kiosk.menu_manager'   => true,
                    'ai.assistant'         => true,
                    'ai.voice_agent'       => true,
                    'branding.white_label' => true,
                    'api.access'           => true,
                    'locations.max'        => null,
                    // Legacy & UI Compatibility Aliases
                    'insights'             => true,
                    'reservations'         => true,
                    'configuration'        => true,
                    'provisioning'         => true,
                    'billing_plan'         => true,
                    'menu_builder'         => true,
                    'floor_plan'           => true,
                    'social_integration'   => true,
                    'pos_terminal'         => true,
                    'staff_management'     => true,
                    'financial_reports'    => true,
                    'ai_automation'        => true,
                    'online_ordering'      => true,
                    'inventory_tracking'   => true,
                    'ai_voice_agent'       => true,
                    'waitlist_automation'  => true,
                    'branch_management'    => true,
                    'public_api'           => true,
                    'franchise_tools'      => true,
                    'white_label_website'  => true,
                ],
                'is_active' => true,
            ],
        ];

        foreach ($plans as $plan) {
            SubscriptionPlan::updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }
    }
}
